### ISSUE TITLE
Enterprise not compatible with numpy 1.14.0

### ISSUE THREAD

**Issue by CaseyMcGrath** [nanograv/enterprise#147]
Sarah Vigeland and I were just troubleshooting a problem I was encountering when trying to run the continuous wave search code.  We found that the latest version of numpy (1.14.0) doesn't seem to be compatible with enterprise.  Here is a look at some of the documentation on the that latest numpy release:
https://github.com/numpy/numpy/releases

It sort of looked like from the error messages that I was getting that something was wrong with the _np.einsum_ function, which appears to be under the "highlights" as one of the things that just changed in this release.  (Sorry, I didn't take a screen-shot of the actual error message before I closed the terminal)

**Comment by jellis18** [comment]
@CaseyMcGrath, you are right. The problem is with `np.einsum` and version 1.14.0. The default behavior has changed to use `optimize=True` instead of `optimize=False`. I don't know exactly what this does but it seems to break things. 

I have tried to go through and add `optimize=False` to all `np.einsum` calls and that seems to work when using `tempo2` as a pulsar backend but not for `PINT` because it uses `astropy` internally which also has this [bug](https://github.com/astropy/astropy/issues/7051). 

The easiest thing for you to do is to revert back to `numpy` v1.13 for now until this gets sorted out with `numpy` and `astropy`. I will also put this in the `requirements.txt` file.

**Comment by CaseyMcGrath** [comment]
Ok, glad that was of help.  Sarah and I did just revert back to the v1.13 version to continue running the code, and that worked fine.
