### ISSUE TITLE
PINTPulsar does not check for coordinate units

### ISSUE THREAD

**Issue by NihanPol** [nanograv/enterprise#363]
I am trying to read in non-nanograv and non-PTA data, where the position of the pulsar is given in equatorial coordinates (as opposed to ecliptic coordinates used in nanograv), where RA is in units of hhmmss. 

Then enterprise pulsar object does not check for units, assuming they are supplied in radians, which results in an incorrect position used for these pulsars.

**Comment by scottransom** [comment]
*facepalm*

**Comment by vallis** [comment]
Is this a PINT issue or enterprise? If PINT has these as astropy Quantity values with units, can you propose code to fix the problem?

**Comment by vhaasteren** [comment]
This is fixed by #370.

However, note that we do need to pay more attention to units between tempo2 and PINT. The units of the designmatrix are not compatible yet, and it's not easy to determine the units of the tempo2 designmatrix in general. PINT does a good job of tracking units. In tempo2, the units of the designmatrix unfortunately seem to not all be equal to the corresponding units of the designmatrix (though I'd like to check this more).

I had difficulty matching the PMRA and PMDEC units between PINT and tempo2. The other astrometry parameters I managed.
